//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmsVisualization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmsVisualization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Sort.
        /// </summary>
        public static string BubbleSortTxt {
            get {
                return ResourceManager.GetString("BubbleSortTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elements and.
        /// </summary>
        public static string ElementsTxt {
            get {
                return ResourceManager.GetString("ElementsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate an array of elements.
        /// </summary>
        public static string GenerateAnArrayOfText {
            get {
                return ResourceManager.GetString("GenerateAnArrayOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion Sort.
        /// </summary>
        public static string InsertionSortTxt {
            get {
                return ResourceManager.GetString("InsertionSortTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the algorithm.
        /// </summary>
        public static string RunAlgorithmTxt {
            get {
                return ResourceManager.GetString("RunAlgorithmTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaker Sort.
        /// </summary>
        public static string ShakerSortTxt {
            get {
                return ResourceManager.GetString("ShakerSortTxt", resourceCulture);
            }
        }
    }
}
